Library refresh
xmos/lib_ethernet pull request #54
Opened 2024-10-25 14:43 UTC by ed-xmos

- [ ]  Remove old examples
- [ ]  XCCM
- [ ]  Docs (xmosdoc)
- [ ]  Jenkins
- [ ]  lib_checks
- [ ]  tests to use XCCM
- [ ]  tests update to testsupport
- [ ]  New lib style

2024-11-11 12:58 UTC, shuchitak requested changes
Requested changes related to removing the ADAT references from README, looks good otherwise.

2024-11-11 12:58 UTC, shuchitak commented on tests/test_time_rx_tx.py
> +# I had problems with the comparison tester putting a newline in the expected regex so wrote custom one and replaced create_expect
If this is fixing a general problem, maybe we upstream it into the test_support repo

2024-11-11 15:15 UTC, ed-xmos commented on README.rst
> +lib_adat: ADAT lightpipe
Ooops - fixed

2024-11-11 15:16 UTC, ed-xmos commented on tests/test_time_rx_tx.py
> +# I had problems with the comparison tester putting a newline in the expected regex so wrote custom one and replaced create_expect
I didn't get to the bottom of it. It was only that test and took ages to figure out a workaround. I'll stick it on the list for later as it's not a show stopper.

2024-11-11 15:17 UTC, ed-xmos commented on examples/AN00199_gigabit_ethernet_demo_explorerkit/Makefile
> +XCC_FLAGS_icmp.xc = $(XCC_FLAGS) -Wno-reinterpret-alignment
Hmm, thinking about it maybe not. But if I remove this we should have a legacy build test to make sure xcommon works.

2024-11-12 11:52 UTC, shuchitak requested changes
Requested changes about the rst heading level. Looks good otherwise!

2024-11-12 14:07 UTC, shuchitak approved these changes

2024-11-12 14:39 UTC, merged